version: '3'

services:

  redis-server:
    image: redis:alpine
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  go-api:
    build:
      context: ./go-api
      dockerfile: Dockerfile
    expose:
      - "9090"
    depends_on:
      - redis-server
    environment:
      - PORT=9090
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis-server:6379

  node-socketio1:
    build:
      context: ./nodejs-socketio
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - PORT=3000
      - NAME=SOCKETIO_1
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis-server:6379
    depends_on:
      - redis-server

  node-socketio2:
    build:
      context: ./nodejs-socketio
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - PORT=3000
      - NAME=SOCKETIO_2
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis-server:6379
    depends_on:
      - redis-server

  nginx-server:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - go-api
      - node-socketio1
      - node-socketio2
